configuration:
  groupId: ausfGroup001
  nrfUri: http://nrf:8081
  sbi:
    bindingIPv4: 0.0.0.0
    port: 29509
    registerIPv4: 1.1.1.1
    scheme: https
  serviceNameList:
    - nausf-auth
info:
  description: AUSF initial local configuration
  version: 1.0.0
logger:
  AMF:
    ReportCaller: false
    debugLevel: info
  AUSF:
    ReportCaller: false
    debugLevel: info
  Aper:
    ReportCaller: false
    debugLevel: info
  CommonConsumerTest:
    ReportCaller: false
    debugLevel: info
  FSM:
    ReportCaller: false
    debugLevel: info
  MongoDBLibrary:
    ReportCaller: false
    debugLevel: info
  N3IWF:
    ReportCaller: false
    debugLevel: info
  NAS:
    ReportCaller: false
    debugLevel: info
  NGAP:
    ReportCaller: false
    debugLevel: info
  NRF:
    ReportCaller: false
    debugLevel: info
  NamfComm:
    ReportCaller: false
    debugLevel: info
  NamfEventExposure:
    ReportCaller: false
    debugLevel: info
  NsmfPDUSession:
    ReportCaller: false
    debugLevel: info
  NudrDataRepository:
    ReportCaller: false
    debugLevel: info
  OpenApi:
    ReportCaller: false
    debugLevel: info
  PCF:
    ReportCaller: false
    debugLevel: info
  PFCP:
    ReportCaller: false
    debugLevel: info
  PathUtil:
    ReportCaller: false
    debugLevel: info
  SMF:
    ReportCaller: false
    debugLevel: info
  UDM:
    ReportCaller: false
    debugLevel: info
  UDR:
    ReportCaller: false
    debugLevel: info
  WEBUI:
    ReportCaller: false
    debugLevel: info
