configuration:
  nrfUri: http://nrf:8081
  nsiList:
  - nsiInformationList:
    - nrfId: http://nrf:8081/nnrf-nfm/v1/nf-instances
      nsiId: 22
    snssai:
      sd: "010203"
      sst: 1
  nssfName: NSSF
  sbi:
    bindingIPv4: 0.0.0.0
    port: 29531
    registerIPv4: 1.1.1.1
    scheme: https
  serviceNameList:
  - nnssf-nsselection
  - nnssf-nssaiavailability
info:
  description: NSSF initial local configuration
  version: 1.0.0
